from setuptools import setup, find_packages

setup(
    name='funwave_ds',  # Match this to your actual package folder name
    version='0.1.0',
    description='Python tools for FUNWAVE.',
    author='Ryan Schanta',
    author_email='rschanta@udel.edu',
    url='https://github.com/rschanta/FUNWAVE_DS',
    packages=find_packages(),  # Automatically finds submodules
    install_requires=[
        'absl-py>=2.1',
        'astunparse>=1.6',
        'certifi>=2024.7',
        'charset-normalizer>=3.3',
        'contourpy>=1.2',
        'cycler>=0.12',
        'flatbuffers>=24.3',
        'fonttools>=4.53',
        'gast>=0.6',
        'google-pasta>=0.2',
        'h5py>=3.11',
        'idna>=3.7',
        'keras>=3.4',
        'kiwisolver>=1.4',
        'markupsafe>=2.1',
        'matplotlib>=3.9',
        'mdurl>=0.1',
        'ml-dtypes>=0.4',
        'namex>=0.0.8',
        'numpy>=1.26',
        'opencv-python>=4.10',
        'opt-einsum>=3.3',
        'optree>=0.12',
        'packaging>=24.1',
        'pandas>=2.2',
        'pillow>=10.4',
        'protobuf>=4.25',
        'pygments>=2.18',
        'pyparsing>=3.1',
        'python-dateutil>=2.9',
        'pytz>=2024.1',
        'requests>=2.32',
        'rich>=13.7',
        'scipy>=1.14',
        'termcolor>=2.4',
        'typing-extensions>=4.12',
        'tzdata>=2024.1',
        'urllib3>=2.2',
        'werkzeug>=3.0',
        'wheel>=0.43',
        'wrapt>=1.16',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',  # Adjust as needed
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.11',
        'License :: OSI Approved :: MIT License',  
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.11',
)
